### ISSUE TITLE
Interface para TS

### ISSUE THREAD

**Issue by gabrielmtns** [BrasilAPI/cep-promise#168]
Fala galera, beleza!?

Apenas uma sugestão simples; 
![image](https://user-images.githubusercontent.com/35817813/82705587-48252f00-9c4e-11ea-8b9c-769fceef89b3.png)

Um export nessa interface CEP ia ajudar a galera do typescript.  Ou até um @ types/ também.. . 

Posso estar viajando ou não ter achado esse export em algum lugar 

Mas tive que alterar manualmente para poder usar legal no TS:
![image](https://user-images.githubusercontent.com/35817813/82706173-72c3b780-9c4f-11ea-9f60-7734b62a7778.png)
![image](https://user-images.githubusercontent.com/35817813/82706085-490a9080-9c4f-11ea-8078-0ea9398a7d33.png)

**Comment by SergioVago** [comment]
Eu abri um PR https://github.com/filipedeschamps/cep-promise/pull/192 com essa exportação. Só esperar alguém aprovar agora

**Comment by lucianopf** [comment]
Boa tarde galera!! 

Primeiramente perdão a demora 😢 

Eu confesso que entendo bem pouco de TS, mas fiquei com uma dúvida, não seria esse export da interface esse mesmo export aqui? https://github.com/filipedeschamps/cep-promise/blob/master/index.d.ts#L16

**Comment by SergioVago** [comment]
Esse export exporta só a função pra usar o buscador de cep. Com o export da interface "CEP", a gnt tem acesso à tipagem separado

**Comment by lucianopf** [comment]
Ahhh sim, boa galera! 🚀

**Comment by bearkfear** [comment]
> Ahhh sim, boa galera! 🚀

Lu, exportando a “interface” nós conseguimos usar em nossas próprias funções, tipando argumentos e afins. O index.d.ts acaba exportando o modulo globalmente para que o TypeScript entenda o que é aquele pacote, mas para implementações usando a lib em escopo acaba sendo necessária uma exportação de “interface”. Comentei sobre converter a lib para TS em uma issue #169 onde eu acredito que seja o ideal atualmente, e também é uma forma de auto-documentação e auto-teste já que não precisaríamos confirmar os tipos dos dados já que eles já estão previamente estabelecidos.

**Comment by hadnet** [comment]
Poderia haver um type para o objeto erro, assim como há para CEP:

```ts
type CepError = {
  name: string;
  message: string;
  type: 'service_error' | 'validation_error';
  errors: {
    message: string;
    service: 'brasilapi' | 'correios' | 'viacep' | 'widenet';
  }[];
};
```
