### ISSUE TITLE
Outra endpoint Correios

### ISSUE THREAD

**Issue by DavidNery** [BrasilAPI/cep-promise#202]
Estava à procura de um serviço dos correios e, quase sem querer, achei outra endpoint de CEP dos correios, bem mais simples que a atual que o `cep-promise` está usando.

Na atual, é utilizado o esquema SOAP. A que encontrei utiliza `urlparams`, o que é bem mais simples e fácil de entender, até para os desenvolvedores.

Enfim, a endpoint é essa: `https://buscacepinter.correios.com.br/app/endereco/carrega-cep-endereco.php?endereco={cep}&tipoCEP=ALL`. Não sei se faz sentido alterar a atual, mas, como falei, na minha opinião, deixa o código um pouco mais fácil de entender, nem que seja da ordem de 10^-3.

**Comment by DavidNery** [comment]
Opa, agora que vi que já tem um pull request utilizando este endpoint. Perdão.

PR #199

**Comment by lucianopf** [comment]
De forma alguma vc precisa se desculpar @DavidNery ! ^^

Muito obrigado pela sugestão!!! ❤️ 

Por sorte dessa vez o querido @mshlz já havia criado um PR pra essa API mas se não tivesse topava muito criar um novo PR em colaboração contigo! 😬
