### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by luka-rmar** [BrasilAPI/cep-promise#203]
Em minha requisição pelo reactjs está vindo o seguinte erro:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://viacep.com.br/ws/01310940/json/. (Reason: header ‘user-agent’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response)`

Alguma solução?

Função utilizada:

```
import cep_promoise from 'cep-promise';
import {states} from './Cities_States';

export async function getAddressProfile (zipcode) {

  try {
    const response = await cep_promoise(zipcode);

    return {
     ...response,
      state: states.find(data => data.sigla === response.state).nome
    };

  } catch (err) {
      return err;
  }
}
```

**Comment by ivancorrea** [comment]
O set que o cep-promise faz do User Agent precisa ser removido (condicionado) para o uso no client. Já existe pull request para corrigir isto.

**Comment by lucianopf** [comment]
Boa, bora tocar isso @ivancorrea !!

**Comment by lucianopf** [comment]
Boa @ivancorrea, vou tocar isso esse fds! 🙏 😬

**Comment by lucianopf** [comment]
@luka-rmar e @ivancorrea fiz o merge e a publicação do fix que o Ivan comentou e parece ter funcionado direitinho 🙌 

Conseguem pfv testar e confirmar? 🙏 😬 

Muito obrigado galera!! ❤️ 

https://github.com/BrasilAPI/cep-promise/pull/189#issuecomment-739084592

**Comment by luka-rmar** [comment]
Fantástico.
Funcionou perfeitamente.

Um forte abraço a toda equipe e meus agradecimentos.

**Comment by juizmill** [comment]
Pra mim está retornando este erro!

![image](https://user-images.githubusercontent.com/1959742/109697133-3caf4e80-7b64-11eb-9bf5-740ae7fa4fc6.png)

**Comment by ivancorrea** [comment]
> Pra mim está retornando este erro!
> 
> ![image](https://user-images.githubusercontent.com/1959742/109697133-3caf4e80-7b64-11eb-9bf5-740ae7fa4fc6.png)

Este domínio não existe. Deve estar hard coded no código...
