### ISSUE TITLE
Erro Atualização Angular 11

### ISSUE THREAD

**Issue by denniscm** [BrasilAPI/cep-promise#205]
Olá,

Eu fiz a atualização da minha aplicação do Angular 10 para o Angular 11, ao iniciar a aplicação eu recebo o seguinte erro:

```
Error: node_modules/cep-promise/index.d.ts:16:3 - error TS2309: An export assignment cannot be used in a module with other exported elements.
16   export = cep
```

Alguém já passou por isso ou soube como resolver?

Obrigado!

**Comment by marcusmaialima** [comment]
Bom dia @denniscm 

Eu tive esse erro na linha 16 também e o que eu fiz foi o seguinte, onde está export = cep tu exporta por default igual o que eu coloquei abaixo.

`export default cep`

Espero ter ajudado e vou tentar fazer um PR e verificar com o pessoal pra ver se corrige :)

**Comment by gleisonkz** [comment]
@marcusmaialima cara vlw de mais, eu estava passando pelo mesmo problema.

**Comment by lucianopf** [comment]
Muito obrigado @marcusmaialima ! ❤️ 

@denniscm o problema foi resolvido conforme a sugestão do querido @marcusmaialima ?

**Comment by marcusmaialima** [comment]
Por nada @lucianopf!!! <3

Que bom que conseguiu resolver @gleisonkz 

O importante é conseguir resolver o problema :)

**Comment by denniscm** [comment]
Obrigado @marcusmaialima!

@lucianopf, O problema foi resolvido, fiz a alteração indicada pelo Marcus e também tive que mudar a chamada nos componentes.

Antes eu fazia a chamada assim:
```
import * as cep from 'cep-promise';
```
Para funcionar corretamente tive que mudar para: 

```
import cep from 'cep-promise';
```

Obrigado a todos pela atenção, agora está tudo certinho!

**Comment by marcusmaialima** [comment]
Que bacana @denniscm!!

Fico feliz em ter conseguido ajudar no problema :)

**Comment by gleisonkz** [comment]
@lucianopf  tem alguma previsão para quando está alteração sugerida pelo @marcusmaialima será incluída?

**Comment by lucianopf** [comment]
Essa semana @gleisonkz !!

Vou dar um gás nas pendências do BrasilAPI 😬 🙏

**Comment by KirstenStake** [comment]
@lucianopf any update on when this will be included in a release please?

**Comment by lucianopf** [comment]
Hoje de tarde @KirstenStake , perdão a demora!

**Comment by lucianopf** [comment]
Alteração publicada no pacote na versão `4.0.4` ❤️ 

Perdão a demora @KirstenStake =/
