### ISSUE TITLE
Atualização de versão no npm

### ISSUE THREAD

**Issue by gustavofoa** [BrasilAPI/cep-promise#209]
A versão atual publicada no npm 4.0.3 apresenta este erro de typescript:

```
ERROR in node_modules/cep-promise/index.d.ts(16,3): error TS2309: An export assignment cannot be used in a module with other exported elements.
```

Verifiquei que o código já foi corrigido, porém a correção ainda não foi publicada no npm.

**Comment by lucianopf** [comment]
Muito obrigado @gustavofoa !

Alteração publicada no pacote na versão 4.0.4 ❤️
