### ISSUE TITLE
Problema com testes

### ISSUE THREAD

**Issue by LorhanSohaky** [BrasilAPI/cep-promise#213]
Não sei se é um problema comum, mas me parece que os testes estão instáveis. Acabei de rodar e deu erro

![image](https://user-images.githubusercontent.com/16273730/111782375-b602ad00-8897-11eb-91b6-c08b719e1888.png)

**Comment by murilohns** [comment]
@LorhanSohaky, o único teste que sei que está intermitente atualmente é o do endpoint `ibge/uf`, por conta do serviço utilizado no endpoint.

Os testes de CEP não deveriam estar intermitentes 🤔

**Comment by lucianopf** [comment]
Booa mestres! Esses são testes e2e, de fato vão nos provedores externos validar que ta tudo "ok".

Infelizmente eles são um pouco instáveis e geram alguma intermitência =/

Mesmo com essa intermitência, como a interface dos queridos podem ser alteradas em qualquer momento ainda prefiro a intermitência do que a integração quebrar :cry:  

O que acham?

**Comment by LorhanSohaky** [comment]
Sim sim, é que se passar nos testes for um requisito muito forte, então pode ser um problema
