### ISSUE TITLE
Erro para resolver o DNS

### ISSUE THREAD

**Issue by LucasOAlves** [BrasilAPI/cep-promise#218]
Olá estou tento um problema ao tentar requisitar qualquer um CEP sempre me retorna _net::ERR_NAME_NOT_RESOLVED_
 
 Print do erro para exemplificar:
![image](https://user-images.githubusercontent.com/15001601/119026138-366a8a80-b97b-11eb-8919-dc37b73349dc.png)

Quando tento acessar a url da requisição diretamente no navegador com uma internet cabeada ou no celular com o 4G.  Recebo o seguinte erro:

![image](https://user-images.githubusercontent.com/15001601/119026395-7df11680-b97b-11eb-82e6-f5662635ffe1.png)

Alguma ideia do que pode ser ?

Testei com as duas últimas versões da biblioteca.

**Comment by ivancorrea** [comment]
@LucasOAlves 
Erro de DNS. O domínio "cep.widenet.host" não existe

**Comment by LucasOAlves** [comment]
@ivancorrea Então eu estou fazendo exatamente como está na documentação e ele está fazendo uma requisição para esse domínio. 

Dei uma olhada nas issues mais antigas, tem outra pessoa com o mesmo problema: 
https://github.com/BrasilAPI/cep-promise/issues/203#issuecomment-789121313

**Comment by ivancorrea** [comment]
@LucasOAlves 
Vc não está fazendo nada errado.

Este domínio está hard coded no source do projeto.

**Comment by ivancorrea** [comment]
Pra resolver rapidamente ai no seu projeto. Voce pode passar os providers como configuracao. Dessa forma pode excluir este que está com erro:

cep('01450000', { timeout: 5000, providers: ['brasilapi', 'correios', 'viacep'] })

**Comment by LucasOAlves** [comment]
@ivancorrea Muito obrigado, vou testar aqui para ver

**Comment by lucianopf** [comment]
Galera to achando que na verdade não tem nenhum problema com o provedor não hein :eyes: (não constantemente) 

![image](https://user-images.githubusercontent.com/8251208/119034817-32436a80-b985-11eb-99d1-220ae22c154f.png)

Quando um dos provedores retorna um erro inesperado pode ser que ele reclame de CORS, mas isso não é a causa original do  problema

**Comment by lucianopf** [comment]
:man_facepalming: nvm, falei de outro domínio msm, perdão

**Comment by lucianopf** [comment]
É... aparentemente eles mudaram a rota e a interface do serviço e precisamos atualizar o provedor :cry: 

Vlw pelo aviso mestre, e sugiro seguir com a recomendação do querido @ivancorrea  (apesar de se manter como está não deve estar impactando na sua aplicação fora o log errado)

**Comment by LucasOAlves** [comment]
@lucianopf Aqui ele não estava finalizando a request então não me trazia nenhum dado, vou continuar testando aqui. 

Esqueci de dizer no começo mas estou utilizando dentro de um projeto em Angular 11. Não sei se faz diferença.

**Comment by LucasOAlves** [comment]
@lucianopf @ivancorrea Deixando com os providers setados ele funcionou, muito obrigado.

**Comment by LucasOAlves** [comment]
@lucianopf Descobri mais um problema, porém relacionado agora ao provider dos correios. Sempre que eu adiciono ele recebo o seguinte erro: 

![image](https://user-images.githubusercontent.com/15001601/119157653-cbc55780-ba2b-11eb-81a0-4e0d0b40cf5d.png)

Dai só removendo ele da listagem de provider funciona normalmente.
