### ISSUE TITLE
Problemas com a versão 3.0.9

### ISSUE THREAD

**Issue by Shelps** [BrasilAPI/cep-promise#241]
Estou tendo problemas com a versão 3.0.9 do cep-promise, não está retornado o endereço.
O que poder isso ?

**Comment by Shelps** [comment]
<img width="945" alt="Captura de Tela 2022-04-12 às 16 27 00" src="https://user-images.githubusercontent.com/6770847/163038689-869aeb97-c9b7-4d4c-9333-93d2d5e1edd3.png">

**Comment by AndreLSilva** [comment]
Eu tive esse mesmo problema, atualizei para a versão mais recente e voltou a funcionar.

**Comment by Shelps** [comment]
Certo, obrigado
