### ISSUE TITLE
widenet apenas para consulta web

### ISSUE THREAD

**Issue by ericksprengel** [BrasilAPI/cep-promise#244]
Olá, pessoal.

Notei que o provider `widenet` estava dando uma resposta de erro equivalente a um `Too Many Requests (429)` após fazer mais de 9 requests para o serviço.
Ao entrar em contato com o pessoal da widenet, eles nos informaram sobre regras de segurança deles e que o serviço é feito para ser utilizado apenas no frontend.
Acredito que vale uma discussão sobre colocar o `widenet` apenas para requests no fronend (https://github.com/BrasilAPI/cep-promise/blob/master/src/services/index.js#L9).
O que acham?

### Response para as primeiras 9 requests:

status code: `200`
```json
{
    "status": 200,
    "ok": true,
    "code": "04279-080",
    "state": "SP",
    "city": "São Paulo",
    "district": "Vila Dom Pedro I",
    "address": "Rua do Parque",
    "statusText": "ok"
}
```

### Response para 10ª request ou posteriores:

status code: `200` *
```json
{
    "status": 400,
    "ok": false,
    "message": "Blocked by flood",
    "statusText": "bad_request"
}
```

\* apesar de o body estar com `"status": 400`, o status code da request é 200 mesmo.

**Comment by rafas** [comment]
Olá @ericksprengel 

Nós estamos mudando o funcionamento da apicep.com (antigo widenet), e disponibilizando um "endpoint" que não tem limite de consulta.

Enviei uma PR agora com a alteração, e talvez demore um pouco pro pessoal fazer o review, enviar pro npm e etc, mas o acesso já está público pra quem precisar usar.

Mais detalhes da PR: https://github.com/BrasilAPI/cep-promise/pull/248

**Comment by ericksprengel** [comment]
closed by #256 
release on version 4.4.0
